### ISSUE TITLE
Use msg.Process

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/haz-ua-consumer#2]
Hi,

please could you use msg.Process in this?  It's needed for the metrics.

**Comment by junghao** [comment]
I thought it's already there?

https://github.com/GeoNet/haz-ua-consumer/blob/master/haz-ua-consumer.go#L44
<pre>
		if !msg.Process(&h) {
			dx <- r.ReceiptHandle
		}
</pre>

**Comment by gclitheroe** [comment]
Sorry!  My mistake.
